// SPDX-License-Identifier: MIT OR Apache-2.0

//! Native eager/lazy grammar and exact-byte structured projection.

use std::any::Any;
use std::fmt;
use std::panic::{AssertUnwindSafe, catch_unwind};

use llama_cpp_4::sampling::LlamaSampler;
use llama_cpp_4::token::LlamaToken;
use llama_cpp_4::token::data::LlamaTokenData;
use llama_cpp_4::token::data_array::LlamaTokenDataArray;
use logit_loom::{
    ActivationPhaseV1, ActivationTelemetryDispositionV1, ByteFeedbackReceiptV1,
    ByteFeedbackStepReceiptV1, CandidateMode, ControlFlow, Digest, GenerationFinish,
    GenerationReceipt, MAX_STRUCTURED_CANDIDATES, ObservedToken, ObserverSet, Pipeline,
    StructuredAttemptDispositionV1, StructuredAttemptReceiptV1, StructuredCompilationReceiptV1,
    StructuredMechanicIdentityV1, StructuredProjectionPlanV1, StructuredProjectionReceiptV1,
    StructuredValidationReceiptV1, StructuredValidationStatusV1, TokenId, structured_output_digest,
    structured_tokens_digest,
};

use crate::{
    Error, Model, Session, StateSnapshot, sampler::build_sampler_v2, session::GenerationOutput,
};

/// Maximum aggregate token-piece bytes retained by a prepared tokenizer table.
pub const MAX_STRUCTURED_TOKENIZER_TABLE_BYTES: usize = 64 * 1024 * 1024;
/// Maximum canonical artifact or validation-report bytes hashed per attempt.
pub const MAX_STRUCTURED_VALIDATION_EVIDENCE_BYTES: usize = 1024 * 1024;

const RETAINED_ERROR_BYTES: usize = 512;

/// One exact model-tokenizer candidate presented to byte feedback.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ByteFeedbackCandidate<'a> {
    /// Exact tokenizer ID.
    pub token: TokenId,
    /// Exact token-piece bytes, which need not be UTF-8.
    pub piece: &'a [u8],
    /// Whether the loaded vocabulary classifies the token as end-of-generation.
    pub end_of_generation: bool,
}

/// Bounded implementation error from exact-byte feedback.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ByteFeedbackError {
    message: String,
}

impl ByteFeedbackError {
    /// Creates an implementation error. The native adapter bounds retained
    /// text when crossing the callback boundary.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl fmt::Display for ByteFeedbackError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for ByteFeedbackError {}

/// Stateful exact-byte candidate feedback for one structured attempt.
pub trait ByteFeedback {
    /// Resets implementation state at the exact common causal boundary.
    ///
    /// # Errors
    ///
    /// Returns an implementation-defined reset failure.
    fn reset(&mut self, causal_tokens: &[TokenId]) -> Result<(), ByteFeedbackError>;

    /// Returns whether one exact token piece may extend current symbolic state.
    ///
    /// # Errors
    ///
    /// Returns an implementation-defined decision failure.
    fn allows(&self, candidate: ByteFeedbackCandidate<'_>) -> Result<bool, ByteFeedbackError>;

    /// Admits one selected non-EOG token piece after native causal admission.
    ///
    /// # Errors
    ///
    /// Returns an implementation-defined state-transition failure.
    fn accept(&mut self, candidate: ByteFeedbackCandidate<'_>) -> Result<(), ByteFeedbackError>;

    /// Returns an exact identity for current implementation-local state.
    ///
    /// # Errors
    ///
    /// Returns an implementation-defined state-identity failure.
    fn state_digest(&self) -> Result<Digest, ByteFeedbackError>;

    /// Returns whether current admitted bytes form a complete symbolic
    /// artifact.
    ///
    /// # Errors
    ///
    /// Returns an implementation-defined completion failure.
    fn complete(&self) -> Result<bool, ByteFeedbackError>;
}

/// Installed byte-feedback implementation bound to its public identity.
pub struct InstalledByteFeedback {
    identity: StructuredMechanicIdentityV1,
    implementation: Box<dyn ByteFeedback>,
}

impl InstalledByteFeedback {
    /// Binds one implementation to an exact installed identity.
    pub fn new(
        identity: StructuredMechanicIdentityV1,
        implementation: impl ByteFeedback + 'static,
    ) -> Self {
        Self {
            identity,
            implementation: Box::new(implementation),
        }
    }

    /// Returns the installed implementation identity.
    pub const fn identity(&self) -> &StructuredMechanicIdentityV1 {
        &self.identity
    }
}

/// Read-only authoritative validation input.
pub struct StructuredValidationContext<'a> {
    /// Exact source schema or constraint identity.
    pub constraints: &'a Digest,
    /// Exact generated bytes.
    pub source: &'a [u8],
}

/// Authoritative mechanical validation output before evidence bytes are
/// reduced to digests.
pub struct StructuredValidationOutcome {
    /// Conforming or rejected disposition.
    pub status: StructuredValidationStatusV1,
    /// Canonical parsed bytes, when produced.
    pub canonical_artifact: Option<Vec<u8>>,
    /// Deterministic validation-report bytes, when produced.
    pub validation_report: Option<Vec<u8>>,
    /// Number of constraint violations.
    pub violations: u32,
    /// Number of parse or validation diagnostics.
    pub diagnostics: u32,
}

/// Bounded implementation error from an authoritative validator.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StructuredValidatorError {
    message: String,
}

impl StructuredValidatorError {
    /// Creates an implementation error. The native adapter bounds retained
    /// text when crossing the callback boundary.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl fmt::Display for StructuredValidatorError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for StructuredValidatorError {}

/// Caller-supplied authoritative parser and constraint validator.
pub trait StructuredValidator {
    /// Validates one complete generated byte sequence.
    ///
    /// # Errors
    ///
    /// Returns an implementation-defined validation failure. A mechanical
    /// rejection is a successful call with `Rejected` status, not an error.
    fn validate(
        &mut self,
        context: StructuredValidationContext<'_>,
    ) -> Result<StructuredValidationOutcome, StructuredValidatorError>;
}

/// Installed validator implementation bound to its public identity.
pub struct InstalledStructuredValidator {
    identity: StructuredMechanicIdentityV1,
    implementation: Box<dyn StructuredValidator>,
}

impl InstalledStructuredValidator {
    /// Binds one implementation to an exact installed identity.
    pub fn new(
        identity: StructuredMechanicIdentityV1,
        implementation: impl StructuredValidator + 'static,
    ) -> Self {
        Self {
            identity,
            implementation: Box::new(implementation),
        }
    }

    /// Returns the installed implementation identity.
    pub const fn identity(&self) -> &StructuredMechanicIdentityV1 {
        &self.identity
    }
}

#[derive(Clone)]
struct TokenMetadata {
    token: TokenId,
    piece: Vec<u8>,
    end_of_generation: bool,
}

struct TokenizerTable {
    entries: Vec<TokenMetadata>,
    identity: Digest,
}

impl TokenizerTable {
    fn build(model: &Model) -> Result<Self, Error> {
        let vocabulary = model.vocabulary_size()?;
        if vocabulary > MAX_STRUCTURED_CANDIDATES {
            return Err(Error::Invalid(format!(
                "structured vocabulary exceeds {MAX_STRUCTURED_CANDIDATES} tokens"
            )));
        }
        let mut entries = Vec::with_capacity(
            usize::try_from(vocabulary)
                .map_err(|_| Error::Invalid("vocabulary size exceeds usize".to_owned()))?,
        );
        let mut identities = Vec::with_capacity(entries.capacity());
        let mut aggregate_bytes = 0_usize;
        for raw in 0..vocabulary {
            let raw = i32::try_from(raw)
                .map_err(|_| Error::Invalid("vocabulary token exceeds i32".to_owned()))?;
            let token = TokenId::new(raw)?;
            let piece = model.token_piece(token)?;
            aggregate_bytes = aggregate_bytes.checked_add(piece.len()).ok_or_else(|| {
                Error::Invalid("structured tokenizer byte count overflowed".to_owned())
            })?;
            if aggregate_bytes > MAX_STRUCTURED_TOKENIZER_TABLE_BYTES {
                return Err(Error::Invalid(format!(
                    "structured tokenizer pieces exceed {MAX_STRUCTURED_TOKENIZER_TABLE_BYTES} bytes"
                )));
            }
            let end_of_generation = model.is_end_of_generation(token);
            identities.push((
                token,
                Digest::of_bytes("structured-token-piece-v1", &piece),
                u64::try_from(piece.len())
                    .map_err(|_| Error::Invalid("structured token piece exceeds u64".to_owned()))?,
                end_of_generation,
            ));
            entries.push(TokenMetadata {
                token,
                piece,
                end_of_generation,
            });
        }
        let identity = Digest::of_serializable("structured-tokenizer-table-v1", &identities)?;
        Ok(Self { entries, identity })
    }

    fn get(&self, token: TokenId) -> Result<&TokenMetadata, Error> {
        let index = usize::try_from(token.get())
            .map_err(|_| Error::Invalid("token identifier exceeds usize".to_owned()))?;
        let metadata = self.entries.get(index).ok_or_else(|| {
            Error::Incompatible("candidate token is absent from tokenizer table".to_owned())
        })?;
        if metadata.token != token {
            return Err(Error::Incompatible(
                "tokenizer table order differs from token identifiers".to_owned(),
            ));
        }
        Ok(metadata)
    }
}

/// Runtime output from one explicit projection attempt.
#[derive(Clone, Debug)]
pub struct StructuredAttemptOutput {
    /// Exact generated bytes, including cancelled or rejected output.
    pub bytes: Vec<u8>,
    /// Exact generated non-EOG tokens.
    pub tokens: Vec<TokenId>,
    /// Content-free attempt evidence.
    pub receipt: StructuredAttemptReceiptV1,
    /// Complete terminal receipt when this attempt was selected.
    pub terminal: Option<StructuredProjectionReceiptV1>,
}

/// Single-owner controller for exact rejection recovery and explicit retry.
///
/// The controller borrows one ordinary session for its full lifetime. It
/// never retries internally: each [`Self::attempt`] call is one caller choice.
/// Cancelled and rejected attempts restore the exact initial checkpoint before
/// returning.
pub struct StructuredProjectionController<'borrow, 'model> {
    session: &'borrow mut Session<'model>,
    plan: StructuredProjectionPlanV1,
    compilation: StructuredCompilationReceiptV1,
    boundary: StateSnapshot,
    boundary_identity: Digest,
    tokenizer: TokenizerTable,
    feedback: InstalledByteFeedback,
    validator: InstalledStructuredValidator,
    attempts: Vec<StructuredAttemptReceiptV1>,
    terminal: Option<StructuredProjectionReceiptV1>,
}

impl<'borrow, 'model> StructuredProjectionController<'borrow, 'model> {
    /// Prepares one exact projection boundary without running generation.
    ///
    /// # Errors
    ///
    /// Returns before causal mutation for plan/compiler/component mismatch,
    /// insufficient context, excessive tokenizer metadata, active steering or
    /// activation state, or checkpoint-capture failure.
    pub fn new(
        session: &'borrow mut Session<'model>,
        plan: StructuredProjectionPlanV1,
        compilation: StructuredCompilationReceiptV1,
        feedback: InstalledByteFeedback,
        validator: InstalledStructuredValidator,
    ) -> Result<Self, Error> {
        plan.validate()?;
        compilation.validate_for(&plan)?;
        if feedback.identity != plan.feedback.mechanic {
            return Err(Error::Incompatible(
                "installed byte feedback differs from the projection plan".to_owned(),
            ));
        }
        if validator.identity != plan.validator {
            return Err(Error::Incompatible(
                "installed validator differs from the projection plan".to_owned(),
            ));
        }
        if plan.target_topology != session.model.topology().digest()? {
            return Err(Error::Incompatible(
                "structured projection names another model topology".to_owned(),
            ));
        }
        if session.token_history().is_empty() {
            return Err(Error::Invalid(
                "structured projection requires a prefilled causal boundary".to_owned(),
            ));
        }
        let required_position = session
            .position()
            .checked_add(u64::from(plan.generation.generation.max_tokens))
            .ok_or_else(|| Error::Invalid("structured context bound overflowed".to_owned()))?;
        if required_position > u64::from(session.options().context_size.get()) {
            return Err(Error::Invalid(format!(
                "structured projection requires context through position {required_position}"
            )));
        }
        let tokenizer = TokenizerTable::build(session.model)?;
        let boundary = session.capture_state()?;
        let boundary_identity = boundary.receipt().digest()?;
        Ok(Self {
            session,
            plan,
            compilation,
            boundary,
            boundary_identity,
            tokenizer,
            feedback,
            validator,
            attempts: Vec::new(),
            terminal: None,
        })
    }

    /// Returns the exact compiled projection plan.
    pub const fn plan(&self) -> &StructuredProjectionPlanV1 {
        &self.plan
    }

    /// Returns completed caller-explicit attempt receipts.
    pub fn attempts(&self) -> &[StructuredAttemptReceiptV1] {
        &self.attempts
    }

    /// Returns terminal selected evidence, when selection has completed.
    pub const fn terminal_receipt(&self) -> Option<&StructuredProjectionReceiptV1> {
        self.terminal.as_ref()
    }

    /// Runs exactly one explicit projection attempt.
    ///
    /// This method never retries. Cancellation and authoritative rejection
    /// restore the common checkpoint before returning. A conforming complete
    /// output remains causal and terminal; later attempts are rejected.
    ///
    /// # Errors
    ///
    /// Returns before mutation for component/pipeline/observer mismatch or
    /// exhausted attempts. Callback/native failures restore the boundary when
    /// possible; failed restoration poisons the session.
    #[allow(
        clippy::too_many_lines,
        reason = "one explicit attempt keeps restore, validation, disposition, and receipt commit adjacent"
    )]
    pub fn attempt(
        &mut self,
        pipeline: Option<&mut Pipeline>,
        observers: Option<&mut ObserverSet>,
    ) -> Result<StructuredAttemptOutput, Error> {
        if self.terminal.is_some() {
            return Err(Error::Invalid(
                "structured projection already selected a terminal attempt".to_owned(),
            ));
        }
        let attempt = u32::try_from(self.attempts.len())
            .map_err(|_| Error::Invalid("structured attempt count exceeds u32".to_owned()))?;
        if attempt >= self.plan.maximum_attempts {
            return Err(Error::Invalid(
                "structured projection exhausted its explicit attempt bound".to_owned(),
            ));
        }
        self.validate_runtime_components(pipeline.as_deref(), observers.as_deref())?;
        feedback_reset(
            self.feedback.implementation.as_mut(),
            self.session.token_history(),
        )?;
        let execution = generate_attempt(
            self.session,
            &self.plan,
            &self.tokenizer,
            self.feedback.implementation.as_mut(),
            pipeline,
            observers,
        );
        let (generation, feedback) = match execution {
            Ok(output) => output,
            Err(error) => return self.restore_after_error(error),
        };
        let output = structured_output_digest(&generation.bytes);
        let cancelled = matches!(generation.receipt.finish, GenerationFinish::ObserverStop);
        let (validation, disposition, terminal_state) = if cancelled {
            if let Err(error) = self.restore_boundary() {
                return Err(Error::Poisoned(format!(
                    "structured cancellation could not restore its boundary: {error}"
                )));
            }
            (
                None,
                StructuredAttemptDispositionV1::Cancelled,
                self.boundary_identity.clone(),
            )
        } else {
            let validation = match validate_output(
                self.validator.implementation.as_mut(),
                &self.plan,
                &generation.bytes,
            ) {
                Ok(receipt) => receipt,
                Err(error) => return self.restore_after_error(error),
            };
            match validation.status {
                StructuredValidationStatusV1::Conforms
                    if feedback.complete && !generation.tokens.is_empty() =>
                {
                    let terminal = match self.session.capture_state() {
                        Ok(state) => state,
                        Err(error) => return self.restore_after_error(error),
                    };
                    let terminal_identity = match terminal.receipt().digest() {
                        Ok(identity) => identity,
                        Err(error) => {
                            return self.restore_after_error(Error::Contract(error));
                        }
                    };
                    (
                        Some(validation),
                        StructuredAttemptDispositionV1::Selected,
                        terminal_identity,
                    )
                }
                StructuredValidationStatusV1::Conforms => {
                    return self.restore_after_error(Error::Incompatible(
                        "validator reported conformance for incomplete or empty feedback output"
                            .to_owned(),
                    ));
                }
                StructuredValidationStatusV1::Rejected => {
                    if let Err(error) = self.restore_boundary() {
                        return Err(Error::Poisoned(format!(
                            "structured rejection could not restore its boundary: {error}"
                        )));
                    }
                    (
                        Some(validation),
                        StructuredAttemptDispositionV1::Rejected,
                        self.boundary_identity.clone(),
                    )
                }
            }
        };
        let receipt = StructuredAttemptReceiptV1 {
            attempt,
            output,
            generation: generation.receipt,
            feedback,
            validation,
            disposition,
            boundary_state: self.boundary_identity.clone(),
            terminal_state: terminal_state.clone(),
        };
        if let Err(error) = receipt.digest_for(&self.plan) {
            return self.restore_after_error(Error::Contract(error));
        }
        self.attempts.push(receipt.clone());
        let terminal = if disposition == StructuredAttemptDispositionV1::Selected {
            let terminal = (|| -> Result<StructuredProjectionReceiptV1, Error> {
                let terminal = StructuredProjectionReceiptV1 {
                    plan: self.plan.digest()?,
                    compilation: self.compilation.digest_for(&self.plan)?,
                    boundary_state: self.boundary_identity.clone(),
                    attempts: self.attempts.clone(),
                    selected_attempt: attempt,
                    final_state: terminal_state,
                };
                terminal.validate_for(&self.plan, &self.compilation)?;
                Ok(terminal)
            })();
            let terminal = match terminal {
                Ok(terminal) => terminal,
                Err(error) => {
                    self.attempts.pop();
                    return self.restore_after_error(error);
                }
            };
            self.terminal = Some(terminal.clone());
            Some(terminal)
        } else {
            None
        };
        Ok(StructuredAttemptOutput {
            bytes: generation.bytes,
            tokens: generation.tokens,
            receipt,
            terminal,
        })
    }

    fn validate_runtime_components(
        &self,
        pipeline: Option<&Pipeline>,
        observers: Option<&ObserverSet>,
    ) -> Result<(), Error> {
        let pipeline_identity = pipeline
            .map(|pipeline| pipeline.specification().digest())
            .transpose()?;
        if pipeline_identity != self.plan.transform_pipeline {
            return Err(Error::Incompatible(
                "structured transform pipeline differs from the plan".to_owned(),
            ));
        }
        if let Some(pipeline) = pipeline
            && pipeline.specification().mode()? != self.plan.feedback.mode
        {
            return Err(Error::Incompatible(
                "structured transforms and byte feedback require one candidate exposure".to_owned(),
            ));
        }
        let observer_identity = observers.map(ObserverSet::identity).transpose()?;
        if observer_identity != self.plan.observer_set {
            return Err(Error::Incompatible(
                "structured observer set differs from the plan".to_owned(),
            ));
        }
        Ok(())
    }

    fn restore_after_error<T>(&mut self, error: Error) -> Result<T, Error> {
        match self.restore_boundary() {
            Ok(()) => Err(error),
            Err(restore) => Err(Error::Poisoned(format!(
                "structured failure `{error}` could not restore its boundary: {restore}"
            ))),
        }
    }

    fn restore_boundary(&mut self) -> Result<(), Error> {
        if let Err(error) = self.session.restore_state(&self.boundary) {
            let poisoned = Error::Poisoned(format!(
                "native structured checkpoint restore failed: {error}"
            ));
            self.session.record_poison(&poisoned);
            return Err(poisoned);
        }
        let restored = match self.session.capture_state() {
            Ok(restored) => restored,
            Err(error) => {
                let poisoned = Error::Poisoned(format!(
                    "restored structured checkpoint could not be verified: {error}"
                ));
                self.session.record_poison(&poisoned);
                return Err(poisoned);
            }
        };
        let restored_identity = restored.receipt().digest()?;
        if restored_identity != self.boundary_identity {
            let poisoned = Error::Poisoned(
                "restored structured checkpoint bytes differ from the captured boundary".to_owned(),
            );
            self.session.record_poison(&poisoned);
            return Err(poisoned);
        }
        Ok(())
    }
}

#[allow(
    clippy::too_many_arguments,
    clippy::too_many_lines,
    reason = "one auditable loop owns byte feedback, native admission, callbacks, and receipts"
)]
fn generate_attempt(
    session: &mut Session<'_>,
    plan: &StructuredProjectionPlanV1,
    tokenizer: &TokenizerTable,
    feedback: &mut dyn ByteFeedback,
    mut pipeline: Option<&mut Pipeline>,
    mut observers: Option<&mut ObserverSet>,
) -> Result<(GenerationOutput, ByteFeedbackReceiptV1), Error> {
    session.ensure_healthy()?;
    let generation = &plan.generation.generation;
    let initial_position = session.position;
    let initial_tokens = structured_tokens_digest(&session.token_history)?;
    let initial_token_count = u64::try_from(session.token_history.len())
        .map_err(|_| Error::Invalid("initial structured token count exceeds u64".to_owned()))?;
    if let Some(active) = pipeline.as_deref_mut() {
        active.begin(&session.token_history)?;
    }
    if let Some(active) = observers.as_deref_mut() {
        active.begin(initial_position, generation.max_tokens)?;
    }
    let mut sampler = build_sampler_v2(
        &session.model.native,
        &plan.generation,
        &session.token_history,
    )?;
    let mut output_tokens = Vec::new();
    let mut output_bytes = Vec::new();
    let mut steps = Vec::new();
    let mut finish = GenerationFinish::TokenLimit;

    for step in 0..generation.max_tokens {
        if let Some(active) = observers.as_deref_mut()
            && active.poll()? == ControlFlow::Stop
        {
            finish = GenerationFinish::ObserverStop;
            break;
        }
        if session.position >= u64::from(session.options.context_size.get()) {
            return Err(Error::Invalid(
                "structured generation reached the configured context bound".to_owned(),
            ));
        }
        let (token, step_receipt) = sample_with_feedback(
            session,
            step,
            tokenizer,
            feedback,
            plan.feedback.mode,
            plan.feedback.max_output_bytes,
            &output_bytes,
            &mut sampler,
            pipeline.as_deref_mut(),
        )?;
        steps.push(step_receipt);
        let metadata = tokenizer.get(token)?;
        if metadata.end_of_generation {
            finish = GenerationFinish::EndOfGeneration { token };
            break;
        }
        let next_bytes = output_bytes
            .len()
            .checked_add(metadata.piece.len())
            .ok_or_else(|| Error::Invalid("structured output byte count overflowed".to_owned()))?;
        if next_bytes > usize::try_from(plan.feedback.max_output_bytes).unwrap_or(usize::MAX) {
            return Err(Error::Invalid(
                "selected token exceeds the structured output-byte bound".to_owned(),
            ));
        }
        session.decode_tokens(
            std::slice::from_ref(&token),
            ActivationPhaseV1::Generation,
            false,
            ActivationTelemetryDispositionV1::Admitted,
        )?;
        sampler.accept(LlamaToken::new(token.get()));
        if let Some(active) = pipeline.as_deref_mut() {
            active.accept(token)?;
        }
        feedback_accept(
            feedback,
            ByteFeedbackCandidate {
                token,
                piece: &metadata.piece,
                end_of_generation: false,
            },
        )?;
        output_tokens.push(token);
        output_bytes.extend_from_slice(&metadata.piece);
        if let Some(active) = observers.as_deref_mut()
            && active.observe(ObservedToken {
                token,
                piece: &metadata.piece,
                position: session.position,
            })? == ControlFlow::Stop
        {
            finish = GenerationFinish::ObserverStop;
            break;
        }
        if let Some(index) = matching_stop(&generation.stops, &output_bytes) {
            finish = GenerationFinish::StopSequence {
                index: u32::try_from(index)
                    .map_err(|_| Error::Invalid("stop index exceeds u32".to_owned()))?,
            };
            break;
        }
    }

    let transform_receipt = pipeline
        .as_deref()
        .map(|active| active.receipt().digest())
        .transpose()?;
    let observer_receipts = observers
        .as_deref()
        .map_or_else(Vec::new, ObserverSet::receipts)
        .into_iter()
        .map(|receipt| receipt.digest())
        .collect::<Result<Vec<_>, _>>()?;
    let generation_receipt = GenerationReceipt {
        plan: plan.generation.digest()?,
        initial_position,
        admitted_tokens: u32::try_from(output_tokens.len())
            .map_err(|_| Error::Invalid("structured token accounting exceeds u32".to_owned()))?,
        admitted_bytes: u64::try_from(output_bytes.len())
            .map_err(|_| Error::Invalid("structured byte accounting exceeds u64".to_owned()))?,
        final_position: session.position,
        finish,
        transform_receipt,
        observer_receipts,
    };
    generation_receipt.digest()?;
    let final_state = feedback_state(feedback)?;
    let feedback_receipt = ByteFeedbackReceiptV1 {
        feedback: plan.feedback.digest()?,
        tokenizer: tokenizer.identity.clone(),
        initial_tokens,
        initial_token_count,
        output: structured_output_digest(&output_bytes),
        output_bytes: u32::try_from(output_bytes.len())
            .map_err(|_| Error::Invalid("structured output bytes exceed u32".to_owned()))?,
        accepted_tokens: u32::try_from(output_tokens.len())
            .map_err(|_| Error::Invalid("structured output tokens exceed u32".to_owned()))?,
        steps,
        final_state,
        complete: feedback_complete(feedback)?,
    };
    feedback_receipt.validate_for(&plan.feedback)?;
    Ok((
        GenerationOutput {
            bytes: output_bytes,
            tokens: output_tokens,
            receipt: generation_receipt,
        },
        feedback_receipt,
    ))
}

#[allow(
    clippy::too_many_arguments,
    clippy::too_many_lines,
    reason = "candidate selection and transactional feedback remain one pre-native boundary"
)]
fn sample_with_feedback(
    session: &mut Session<'_>,
    step: u32,
    tokenizer: &TokenizerTable,
    feedback: &dyn ByteFeedback,
    mode: CandidateMode,
    max_output_bytes: u32,
    output: &[u8],
    sampler: &mut LlamaSampler,
    pipeline: Option<&mut Pipeline>,
) -> Result<(TokenId, ByteFeedbackStepReceiptV1), Error> {
    let mut logits = catch_unwind(AssertUnwindSafe(|| session.context.get_logits().to_vec()))
        .map_err(|_| Error::Native("llama.cpp logits were unavailable".to_owned()))?;
    let indices = selected_indices(mode, &logits);
    if indices.is_empty() {
        return Err(Error::Invalid(
            "structured candidate exposure selected no finite logits".to_owned(),
        ));
    }
    let candidate_tokens =
        indices
            .iter()
            .map(|index| {
                TokenId::new(i32::try_from(*index).map_err(|_| {
                    Error::Native("structured candidate token exceeds i32".to_owned())
                })?)
                .map_err(Error::from)
            })
            .collect::<Result<Vec<_>, _>>()?;
    let mut working = indices
        .iter()
        .map(|index| logits[*index])
        .collect::<Vec<_>>();
    if let Some(active) = pipeline {
        active.apply_to_candidates(
            step,
            &session.token_history,
            &candidate_tokens,
            &mut working,
        )?;
    }
    let state = feedback_state(feedback)?;
    let output_prefix = structured_output_digest(output);
    let mut eligible_candidates = 0_u32;
    let mut allowed = Vec::new();
    let mut rejected = Vec::new();
    for (token, logit) in candidate_tokens.iter().copied().zip(&mut working) {
        if logit.is_nan() {
            return Err(Error::Invalid(
                "structured candidate view contains a NaN logit".to_owned(),
            ));
        }
        if *logit == f32::NEG_INFINITY {
            continue;
        }
        eligible_candidates = eligible_candidates
            .checked_add(1)
            .ok_or_else(|| Error::Invalid("eligible candidate count overflowed".to_owned()))?;
        let metadata = tokenizer.get(token)?;
        let within_output_bound = metadata.end_of_generation
            || output
                .len()
                .checked_add(metadata.piece.len())
                .is_some_and(|bytes| {
                    bytes <= usize::try_from(max_output_bytes).unwrap_or(usize::MAX)
                });
        if within_output_bound
            && feedback_allows(
                feedback,
                ByteFeedbackCandidate {
                    token,
                    piece: &metadata.piece,
                    end_of_generation: metadata.end_of_generation,
                },
            )?
        {
            allowed.push(token);
        } else {
            *logit = f32::NEG_INFINITY;
            rejected.push(token);
        }
    }
    if allowed.is_empty() {
        return Err(Error::Invalid(
            "structured byte feedback rejected every eligible candidate".to_owned(),
        ));
    }
    for (index, value) in indices.iter().copied().zip(working) {
        logits[index] = value;
    }
    let data = logits
        .into_iter()
        .enumerate()
        .map(|(index, logit)| {
            let token = i32::try_from(index)
                .map_err(|_| Error::Native("vocabulary token exceeds i32".to_owned()))?;
            Ok(LlamaTokenData::new(LlamaToken::new(token), logit, 0.0))
        })
        .collect::<Result<Vec<_>, Error>>()?;
    let mut candidates = LlamaTokenDataArray::new(data, false);
    sampler.apply(&mut candidates);
    let selected = candidates
        .selected_token()
        .ok_or_else(|| Error::Native("native sampler did not select a token".to_owned()))?;
    let selected = TokenId::new(selected.0)?;
    let receipt = ByteFeedbackStepReceiptV1 {
        step,
        accepted_tokens: step,
        output_bytes: u32::try_from(output.len())
            .map_err(|_| Error::Invalid("structured output prefix exceeds u32".to_owned()))?,
        output_prefix,
        state,
        candidate_tokens: u32::try_from(candidate_tokens.len())
            .map_err(|_| Error::Invalid("candidate count exceeds u32".to_owned()))?,
        eligible_candidates,
        allowed_candidates: u32::try_from(allowed.len())
            .map_err(|_| Error::Invalid("allowed count exceeds u32".to_owned()))?,
        rejected_candidates: u32::try_from(rejected.len())
            .map_err(|_| Error::Invalid("rejected count exceeds u32".to_owned()))?,
        allowed_tokens: structured_tokens_digest(&allowed)?,
        rejected_tokens: structured_tokens_digest(&rejected)?,
    };
    Ok((selected, receipt))
}

fn selected_indices(mode: CandidateMode, logits: &[f32]) -> Vec<usize> {
    match mode {
        CandidateMode::FullVocabulary => (0..logits.len()).collect(),
        CandidateMode::Sparse { limit } => {
            let mut indices = logits
                .iter()
                .enumerate()
                .filter(|(_, value)| value.is_finite())
                .map(|(index, _)| index)
                .collect::<Vec<_>>();
            indices.sort_unstable_by(|left, right| {
                logits[*right]
                    .total_cmp(&logits[*left])
                    .then_with(|| left.cmp(right))
            });
            indices.truncate(usize::try_from(limit).unwrap_or(usize::MAX));
            indices
        }
    }
}

fn validate_output(
    validator: &mut dyn StructuredValidator,
    plan: &StructuredProjectionPlanV1,
    source: &[u8],
) -> Result<StructuredValidationReceiptV1, Error> {
    let result = catch_unwind(AssertUnwindSafe(|| {
        validator.validate(StructuredValidationContext {
            constraints: &plan.constraints,
            source,
        })
    }));
    let outcome = match result {
        Ok(Ok(outcome)) => outcome,
        Ok(Err(error)) => {
            return Err(Error::StructuredValidator(bound_message(error.to_string())));
        }
        Err(payload) => {
            return Err(Error::StructuredValidator(bound_message(format!(
                "validator panicked: {}",
                panic_message(payload.as_ref())
            ))));
        }
    };
    for (field, bytes) in [
        ("canonical artifact", outcome.canonical_artifact.as_deref()),
        ("validation report", outcome.validation_report.as_deref()),
    ] {
        if bytes.is_some_and(|bytes| bytes.len() > MAX_STRUCTURED_VALIDATION_EVIDENCE_BYTES) {
            return Err(Error::Invalid(format!(
                "structured {field} exceeds {MAX_STRUCTURED_VALIDATION_EVIDENCE_BYTES} bytes"
            )));
        }
    }
    let output = structured_output_digest(source);
    let receipt = StructuredValidationReceiptV1 {
        validator: plan.validator.digest()?,
        constraints: plan.constraints.clone(),
        source: output.clone(),
        canonical_artifact: outcome
            .canonical_artifact
            .as_deref()
            .map(|bytes| Digest::of_bytes("structured-canonical-artifact-v1", bytes)),
        validation_report: outcome
            .validation_report
            .as_deref()
            .map(|bytes| Digest::of_bytes("structured-validation-report-v1", bytes)),
        status: outcome.status,
        violations: outcome.violations,
        diagnostics: outcome.diagnostics,
    };
    receipt.validate_for(plan, &output)?;
    Ok(receipt)
}

fn feedback_reset(feedback: &mut dyn ByteFeedback, tokens: &[TokenId]) -> Result<(), Error> {
    feedback_callback("reset", || feedback.reset(tokens))
}

fn feedback_allows(
    feedback: &dyn ByteFeedback,
    candidate: ByteFeedbackCandidate<'_>,
) -> Result<bool, Error> {
    feedback_callback("candidate decision", || feedback.allows(candidate))
}

fn feedback_accept(
    feedback: &mut dyn ByteFeedback,
    candidate: ByteFeedbackCandidate<'_>,
) -> Result<(), Error> {
    feedback_callback("token admission", || feedback.accept(candidate))
}

fn feedback_state(feedback: &dyn ByteFeedback) -> Result<Digest, Error> {
    feedback_callback("state identity", || feedback.state_digest())
}

fn feedback_complete(feedback: &dyn ByteFeedback) -> Result<bool, Error> {
    feedback_callback("completion", || feedback.complete())
}

fn feedback_callback<T>(
    phase: &str,
    callback: impl FnOnce() -> Result<T, ByteFeedbackError>,
) -> Result<T, Error> {
    match catch_unwind(AssertUnwindSafe(callback)) {
        Ok(Ok(value)) => Ok(value),
        Ok(Err(error)) => Err(Error::StructuredFeedback(bound_message(format!(
            "{phase}: {error}"
        )))),
        Err(payload) => Err(Error::StructuredFeedback(bound_message(format!(
            "{phase} panicked: {}",
            panic_message(payload.as_ref())
        )))),
    }
}

fn matching_stop(stops: &[Vec<u8>], output: &[u8]) -> Option<usize> {
    stops.iter().position(|stop| output.ends_with(stop))
}

fn bound_message(mut message: String) -> String {
    if message.len() > RETAINED_ERROR_BYTES {
        let mut end = RETAINED_ERROR_BYTES;
        while !message.is_char_boundary(end) {
            end -= 1;
        }
        message.truncate(end);
    }
    message
}

fn panic_message(payload: &(dyn Any + Send)) -> String {
    payload.downcast_ref::<&str>().map_or_else(
        || {
            payload
                .downcast_ref::<String>()
                .cloned()
                .unwrap_or_else(|| "non-string panic payload".to_owned())
        },
        |message| (*message).to_owned(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sparse_selection_is_ranked_and_token_stable() {
        let logits = [1.0, 2.0, 2.0, f32::NEG_INFINITY];
        assert_eq!(
            selected_indices(CandidateMode::Sparse { limit: 2 }, &logits),
            [1, 2]
        );
    }

    #[test]
    fn callback_messages_are_bounded_without_splitting_utf8() {
        let message = "é".repeat(RETAINED_ERROR_BYTES);
        let bounded = bound_message(message);
        assert!(bounded.len() <= RETAINED_ERROR_BYTES);
        assert!(std::str::from_utf8(bounded.as_bytes()).is_ok());
    }

    #[test]
    fn feedback_panics_are_contained() {
        let result = feedback_callback("test", || -> Result<(), ByteFeedbackError> {
            panic!("synthetic feedback panic");
        });
        assert!(matches!(result, Err(Error::StructuredFeedback(_))));
    }
}
