// SPDX-License-Identifier: MIT OR Apache-2.0

//! Shared, serializable evidence records for model-backed examples.

use std::io::{self, Write as _};

use logit_loom_runtime::{
    AdmissionOutput, CoreError, Digest, GenerationOutput, GenerationReceipt, Loom,
    ModelArtifactReceipt, PrefillReceipt, TokenId,
};
use serde::Serialize;

/// Exact model and backend metadata for one run.
#[derive(Debug, Serialize)]
pub struct RunMetadata {
    /// Exact catalog verification evidence, when a profile loader was used.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profile_artifact: Option<ModelArtifactReceipt>,
    /// Content identity of the caller-supplied model bytes.
    pub model_identity: Digest,
    /// Identity of the native backend build.
    pub backend_identity: Digest,
    /// Human-readable backend compatibility label.
    pub backend_compatibility: String,
    /// Native device descriptions reported for the loaded model.
    pub devices: Vec<String>,
    /// Exact model-loading placement options used by the example.
    pub model_placement: ModelPlacementRecord,
    /// Exact native session allocation used by the example.
    pub session_allocation: SessionAllocationRecord,
}

/// Serializable projection of native model-placement options.
#[derive(Debug, Serialize)]
pub struct ModelPlacementRecord {
    /// Repeating layers requested for accelerator offload.
    pub gpu_layers: u32,
    /// Selected primary accelerator index.
    pub main_gpu: i32,
    /// Debug label for the post-load device policy.
    pub device_policy: String,
}

/// Serializable projection of native session allocation options.
#[derive(Debug, Serialize)]
pub struct SessionAllocationRecord {
    /// Maximum causal context size.
    pub context_size: u32,
    /// Maximum logical decode batch.
    pub batch_size: u32,
    /// Maximum physical decode micro-batch.
    pub micro_batch_size: u32,
    /// Host orchestration thread count.
    pub threads: i32,
}

impl RunMetadata {
    /// Captures model and backend metadata from a loaded loom.
    pub fn capture(loom: &Loom) -> Self {
        let options = loom.options();
        Self {
            profile_artifact: loom.profile_artifact().cloned(),
            model_identity: loom.model_identity().clone(),
            backend_identity: loom.backend_identity().clone(),
            backend_compatibility: loom.backend_compatibility().to_owned(),
            devices: loom.devices().to_vec(),
            model_placement: ModelPlacementRecord {
                gpu_layers: options.model.gpu_layers,
                main_gpu: options.model.main_gpu,
                device_policy: format!("{:?}", options.model.device_policy),
            },
            session_allocation: SessionAllocationRecord {
                context_size: options.session.context_size.get(),
                batch_size: options.session.batch_size,
                micro_batch_size: options.session.micro_batch_size,
                threads: options.session.threads,
            },
        }
    }
}

/// Exact tokenization and causal admission accounting.
#[derive(Debug, Serialize)]
pub struct AdmissionRecord {
    /// Token IDs returned by the model tokenizer.
    pub tokens: Vec<TokenId>,
    /// Tokens causally admitted by the native prefill.
    pub admitted_tokens: u64,
    /// Causal position after prefill.
    pub final_position: u64,
    /// Controlled-prefill accounting, when a monitor was attached.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub receipt: Option<PrefillReceipt>,
}

impl From<AdmissionOutput> for AdmissionRecord {
    fn from(output: AdmissionOutput) -> Self {
        Self {
            tokens: output.tokens,
            admitted_tokens: output.prefill.admitted_tokens,
            final_position: output.prefill.position,
            receipt: output.prefill.receipt,
        }
    }
}

/// Exact generated bytes, token IDs, and mechanical receipt.
#[derive(Debug, Serialize)]
pub struct GenerationRecord {
    /// Content identity of the exact token IDs and output bytes.
    pub output_identity: Digest,
    /// Exact output bytes encoded without a UTF-8 assumption.
    pub bytes_hex: String,
    /// Causally admitted generated token IDs.
    pub tokens: Vec<TokenId>,
    /// Mechanical accounting for the bounded generation call.
    pub receipt: GenerationReceipt,
    /// Content identity of the validated generation receipt.
    pub receipt_identity: Digest,
}

impl TryFrom<GenerationOutput> for GenerationRecord {
    type Error = CoreError;

    fn try_from(output: GenerationOutput) -> Result<Self, Self::Error> {
        let output_identity = Digest::of_serializable(
            "runtime-generation-output-v1",
            &(&output.tokens, &output.bytes),
        )?;
        let receipt_identity = output.receipt.digest()?;
        Ok(Self {
            output_identity,
            bytes_hex: encode_hex(&output.bytes),
            tokens: output.tokens,
            receipt: output.receipt,
            receipt_identity,
        })
    }
}

/// Encodes arbitrary bytes as lowercase hexadecimal text.
pub fn encode_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut encoded = String::with_capacity(bytes.len().saturating_mul(2));
    for byte in bytes {
        encoded.push(char::from(HEX[usize::from(byte >> 4)]));
        encoded.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    encoded
}

/// Writes one pretty JSON value followed by a newline.
pub fn write_json(value: &impl Serialize) -> Result<(), Box<dyn std::error::Error>> {
    let stdout = io::stdout();
    let mut output = stdout.lock();
    serde_json::to_writer_pretty(&mut output, value)?;
    writeln!(output)?;
    Ok(())
}
